name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover tests

      - name: Create artifact
        run: |
          python setup.py sdist
        env:
          BUILD_VERSION: ${{ github.run_id }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: simple-python-project-artifact
          path: dist/
